### ISSUE TITLE
Action on click on notification ?

### ISSUE THREAD

**Issue by Phyks** [knopwob/dunst#163]
Hi,

I'm using dunst as a notification daemon on my system, and I'm using it in particular to display Thunderbird notifications (thanks to the Gnome Integration addon).

Is there any way to change the click action ? I'd like to be able to focus Thunderbird when I click on the notification.

Thanks

**Comment by deiwin** [comment]
Probably for posterity: **press ctrl+shift+period**.

I'm new and had the same question so I started searching. It says [here](https://github.com/knopwob/dunst/blob/master/RELEASE_NOTES.1.0.0) that the context menu can be used to invoke this action. And it looks like the default keyboard shortcut for that is  the aforementioned *ctrl+shift+period*. So there you go.

**Comment by Phyks** [comment]
@deiwin wow, thanks for this, I totally forgot about it.

I tried the shortcut but, as expected, it does not work out of the box. If I understood correctly, I have to manually bind an action to the notifications. Do you have doc about this as well?

Thanks!

**Comment by deiwin** [comment]
You can find information about the configuration here: https://github.com/knopwob/dunst#configuration

The variable you're looking for should be under `[shortcuts]` and should be called `context`. Here's what the relevant parts of my config look like:
```
[shortcuts]

    # Other shortcuts

    # Context menu.
    context = ctrl+shift+period
```

**Comment by Phyks** [comment]
Thanks!

**Comment by brettinternet** [comment]
For anyone that has landed here via search, this is very possible through simple scripting via `dunstify`.

When using `--action`, `dunstify` will either return the action name you specify or a number. The number adheres to the [Notification spec](https://developer.gnome.org/notification-spec/#signals), so if `1` is returned, the notification expired and if `2` is returned then the notification was dismissed by the user. Dismissing occurs in one of three ways:

1. Close notification as defined in `dunstrc`: `close = ctrl+space` (default)
1. Close all notifications as defined in `dunstrc`: `close_all = ctrl+shift+space` (default)
1. Clicking on the notification (✅)

So just handle the result:

```sh
open_player () {
    /usr/bin/spotify --uri="$1" &>/dev/null &
    disown
}

ACTION=$(dunstify -a "$PLAYER" -r "$MSG_ID" -u low --action="openPlayer,Open" \
    "$TRACK_TITLE" "$TRACK_ARTIST - $TRACK_ALBUM"
)

case "$ACTION" in
    "openPlayer" | "2")
        open_player $TRACK_ID
        ;;
esac
```

[See Arch Wiki for more information](https://wiki.archlinux.org/index.php/Dunst#Actions).

**Comment by tsipinakis** [comment]
Thanks the addition!

Some additional things that could work for this:
You can use `do_action` (bound to middle click by default, can be changed to either left or right in the config) paired with an action named `default` which will avoid showing dmenu.

**Comment by brettinternet** [comment]
@tsipinakis That's even better! Then you can differentiate when a shortcut dismisses the notification and when the notification is clicked. Thank you.

[Here's how to customize mouse actions in `dunstrc`](https://github.com/dunst-project/dunst/blob/master/dunstrc#L237).

**Comment by ensismoebius** [comment]
@brettinternet thank you!

**Comment by antoniovillavicencio** [comment]
I landed here because I wanted to click in my notification and execute the action. On the left, if there is an 'A' on the notification it means there is an action attached and if there's an 'U' it means there is an URL. To execute the action with the mouse, you can do it with a middle click. 

[Reference](https://www.mankier.com/1/dunst#Actions)

**Comment by mark2185** [comment]
Is there a way to set a keyboard mapping for `dunstctl action` through the `dunstrc`?

I tried `action = mod1+grave`, but nothing happens. Calling `dunstctl action` works, tho.

**Comment by fwSmit** [comment]
No this is deliberately removed. You can set a shortcut through your DE/WM

**Comment by mark2185** [comment]
> No this is deliberately removed. You can set a shortcut through your DE/WM

That's what I had as a workaround, thanks!

**Comment by daki456** [comment]
Can someone from here explain how can i run my script when i do left click on my mouse to run my script switch_to_workspace (swtiches to my 4 workspace where my vesktop is) because i can't seem to find the workaround. I was only able to make it work when notification pops up, not on left click. here is my config:

`[global]
monitor = 0
width = (0, 500)
height = 100
notification_limit = 0
origin = top-right
offset = 17x17
progress_bar = true
progress_bar_max_width = 500
progress_bar_corner_radius = 0
font = "Noto"
corner_radius = 10
frame_width = 2
mouse_left_click = do_action, close_current
mouse_middle_click = close_current
mouse_right_click = context
transparency = 85
background = "#0e4763"
foreground = "#99CCE5FF"
highlight = "AAE2FFFF"
frame_color = "3D7A99FF"
separator_color = frame
format = "<span color='3D7A99FF'>%s</span>\n%b"
icon_corner_radius = rider.val.rounding
timeout = 3
show_indicators = no

`
